# Default values for tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tektonNamespace: tekton

namespacePermissions:
  user: user
  role: edit

app:
  name: my-app
  namespace: demo
  repo:
    source:
      url: http://gitea.gitea.svc:3000/user/my-app
      revision: main
      user: user
      password: password
    gitops:
      url: http://gitea.gitea.svc:3000/user/my-app-gitops
      revision: main
      user: user
      password: password
      path: "."

routeSubdomain: ""
