---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el
  namespace: {{ .Values.tektonNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-eventlistener
    weight: 100
